name: mtga-analysis
channels:
  - conda-forge
  - defaults
dependencies:
  - python=3.10
  - pandas
  - ipykernel
  - jupyterlab
  - matplotlib
  - seaborn
  - statsmodels
  - pip
  - pip:
    - jupyter-black
